#server:
#  port: 801
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    # MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.242.201:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: cestc01
#  application:
#    name: mall-product
#
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
